### ISSUE TITLE
How often can you open the window before recharge?

### ISSUE THREAD

**Issue by filipre** [meichthys/window_sensors#1]
Hi, 

First of all, nice project! 

According to your [Reddit post](https://www.reddit.com/r/homeassistant/comments/b5zpf0/insanely_cheap_diy_wireless_windowdoor_sensors/) you said that the sensor will last for about a year. However, I was wondering how long it will last in terms of "opening and closing" your window. The related [video](https://www.youtube.com/watch?v=BoYVr2UwWWg) said that the "3V Lithium CR2032 Batteries " will power the device for about 20 openings but you are using a 3.7V battery with higher capacity so I assume it will be a bit higher. Do you have some data on that?

Also, I was wondering whether there exists a better solution to make it last longer. In Germany, we open the windows at least once a day so recharging the battery every 15 - 20 days is quite a lot.

Best!

**Comment by meichthys** [comment]
@filipre Thanks, As for the battery life, most of my windows are still on the second charge so it appears that i'm getting close to 6 months on a charge. That being said, i only open my windows about once a week, so in your use case you might get closer to 2 months, but that's just a guess.

On a side note, if you do decide to get the batteries that i linked to, they may slightly expand after a few months or after recharging. I used a very fine pin and pricked a very small hole in the very outside sheath to prevent the battery from bulging further (This only happened on a few of the batteries, so it could have just been a slight defect in manufacturing). 

In the future i'd like to add to the project a small charging station for the batteries (Currently i just use aligator clips to charge them, but it would be nice to just have a small station that i can swap batteries in and out as needed.

**Comment by filipre** [comment]
I see, thank you!
