### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by dskvr** [meichthys/window_sensors#5]
Parts list has broken links, adds quite a bit of friction for getting started. 

1. 5mm magnet (important)
2. ESP breadboard adapter (less important)  

Generally wouldn't be a big deal but there's no information on magnet dimensions/shape anywhere (5mm is vague), can't really tell from models and none of the photos show the magnet. 

Thank you for this project, looks great!!

**Comment by meichthys** [comment]
These should be fixed with search result links now.
